services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urgencia_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9200:9000"
      - "5173:5173"
    networks:
      - urgencia_net

  webserver:
    image: nginx:alpine
    container_name: urgencia_web
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - urgencia_net

  mysql:
    image: mysql:8.0
    container_name: urgencia_mysql
    restart: always
    environment:
      MYSQL_DATABASE: urgencia_adulto
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: urgencia_user
      MYSQL_PASSWORD: Urg3ncia2025!
    ports:
      - "3307:3306"
    volumes:
      - urgencia_mysql_data:/var/lib/mysql
    networks:
      - urgencia_net

networks:
  urgencia_net:

volumes:
  urgencia_mysql_data: